// Generated by LiveScript 1.4.0
(function(){
  define(['backbone'], function(){
    return Backbone.Model.extend({
      defaults: function(){
        return {
          title: 'empty todo...',
          order: Todos.nextOrder(),
          done: false
        };
      },
      toggle: function(){
        return this.save({
          done: !this.get('done')
        });
      }
    });
  });
}).call(this);
