// Generated by LiveScript 1.4.0
(function(){
  define(['model/todo_model'], function(todo_model){
    return Backbone.Collection.extend({
      model: todo,
      localStorage: new Backbone.LocalStorage('todos'),
      done: function(){
        return this.where({
          done: true
        });
      },
      remaining: function(){
        return this.where({
          done: false
        });
      },
      nextOrder: function(){
        if (!this.length) {
          return 1;
        }
        return this.last().get('ordre') + 1;
      },
      comparator: 'order'
    });
  });
}).call(this);
