// Generated by LiveScript 1.4.0
(function(){
  define(['backbone', 'jquery'], function(){
    return Backbone.View.extend({
      initialize: function(){
        this.listenTo(this.model, 'change', this.render);
        return this.listenTo(this.model, 'destroy', this.remove);
      },
      tagName: 'li',
      template: _.template($('#item-template').html()),
      events: {
        'click .toggle': 'toggleDone',
        'dblclick .view': 'edit',
        'click a.destroy': 'clear',
        'keypress .edit': 'updateOnEnter',
        'blur .edit': 'close'
      },
      toggleDone: function(){
        return this.model.toggle();
      },
      edit: function(){
        this.$el.addClass('editing');
        return this.input.focus();
      },
      close: function(){
        var value;
        return value = this.input.val();
      },
      updateOnEnter: function(){
        if (e.keyCode === 13) {
          return this.close();
        }
      },
      clear: function(){
        return this.model.destory();
      }
    });
  });
}).call(this);
